### ISSUE TITLE
sendMessage method shouldn´t check message to be a string 

### ISSUE THREAD

**Issue by insaneDev** [4yopping/SQSLogger#2]
Since toString method can be overriden in any function, wouldn´t it be nice allow sendMessage to accept a wider range of types for message argument?

function Foo() 
{
}

// toString override added to prototype of Foo class
Foo.prototype.toString = function()
{
    return "Im Foo";
}

sendMessage(new Foo(), null);

**Comment by Quantium** [comment]
Thank you manis, you are free to make a pull request.

**Comment by Quantium** [comment]
The issue was fixed in the version 1.0.2. Closing the issue.

Thanks for reporting.
