### ISSUE TITLE
AWS credentials from config options

### ISSUE THREAD

**Issue by markotom** [4yopping/SQSLogger#4]
I think it would be nice also able to add AWS credentials from the SQSLogger options, like this:

```js
var SQSLogger = require('sqs-logger');
var logger = new SQSLogger({
  accessKeyId: '...',
  secretAccessKey: '...',
  QueueUrl: 'http://...'
});
```

I think we might have more choices to add credentials in this way.

What do you think?

**Comment by Quantium** [comment]
You can use the same authentication methods of [AWS NodeJS SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html)

I certainly recommend to use Credentials from Environment Variables for QA and Staging enviroments and the SDK profiles for local development. 

The environment credentials are __AWS_ACCESS_KEY_ID__ and __process.env.AWS_SECRET_ACCESS_KEY__

Furthermore, you can load a config file using the config loadFromPath function for Production environments:

`````
AWS.config.loadFromPath('./config.json')
````

Even though, if you want to hardcode your credentials (Not recommended at all) you can set them using the config update function:

````AWS.config.update({accessKeyId: 'akid', secretAccessKey: 'secret'});````
